<a href="https://colab.research.google.com/github/nagavenkateshgavini/100daysofML/blob/main/numpy_and_pandas_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
one_d = np.array([1, 2, 3])

In [3]:
one_d

array([1, 2, 3])

In [4]:
two_d = np.array([[1, 2], [3, 4], [5, 6]])

In [5]:
two_d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
arr_zeros = np.zeros([3,2])
arr_zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [7]:
rand_ints = np.random.randint(low=50, high=100, size=(6))
rand_ints

array([98, 82, 96, 73, 54, 80])

In [8]:
np.random.random([6])

array([0.07733358, 0.5721378 , 0.34244568, 0.47730556, 0.83996335,
       0.33839593])

Task 1: Creating a dataset

In [13]:
feature = np.arange(6, 21)
print(feature)
label = 3 * feature + 4
print(label)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


Task 2: Add some noise

In [14]:
noise = np.random.random(15) * 4 - 2

In [15]:
noise

array([ 1.36943487, -1.13998976,  0.85301877, -1.00937131,  0.42738274,
       -1.86928967, -0.7756998 , -0.13366451,  1.13121748, -0.64673614,
       -1.00993793, -1.15775789, -0.52672709, -1.1916801 ,  0.39393292])

In [22]:
label = label + noise

In [23]:
label

array([23.36943487, 23.86001024, 28.85301877, 29.99062869, 34.42738274,
       35.13071033, 39.2243002 , 42.86633549, 47.13121748, 48.35326386,
       50.99006207, 53.84224211, 57.47327291, 59.8083199 , 64.39393292])